### ISSUE TITLE
Forestry Worktable GUI

### ISSUE THREAD

**Issue by ArfourFoulkesayke** [John-Smith-Modded/JSTR-1.7.x#100]
Hi everyone, I recently noticed that the Forestry worktable GUI is not working. The texture is in the pack, but it isn't shown in game. Maybe the texture name changed with a recent update of the mod?

I am currently using version 3.4.0.7 in the Direwolf20 pack, version 1.0.4.

**Comment by Oddface** [comment]
Fixed.
