### ISSUE TITLE
Forestry Saplings

### ISSUE THREAD

**Issue by Kafriah** [John-Smith-Modded/JSTR-1.7.x#110]
I made a few saplings for forestry and I am not positive if they look good enough to be in the pack.
 I would appreciate any advice or thoughts. XD

https://github.com/Kafriah/JSTR-1.7.x/commit/381ee790fa23e64bbd755a1cba7e3fb35b487ce1

Thanks!

**Comment by goldbattle** [comment]
I think they look really good. I really like that cherry one.
All the shadowing on them look to be correct.

**Comment by Kafriah** [comment]
Awesome :D Thank you!

**Comment by lesdmark** [comment]
I think they are quite good as well. Perfectly themed to JSTR!

**Comment by Kafriah** [comment]
Thank you! XD
