### ISSUE TITLE
Storage Drawers

### ISSUE THREAD

**Issue by lesdmark** [John-Smith-Modded/JSTR-1.7.x#112]
Here is some work I've been doing on storage drawers. Let me know what everyone thinks.
![drawers_acacia_front_1](https://cloud.githubusercontent.com/assets/7751260/8016369/8cefe848-0bb0-11e5-90a3-dd8b52827b2a.png)
![drawers_acacia_front_2](https://cloud.githubusercontent.com/assets/7751260/8016368/8cef0450-0bb0-11e5-8386-85400651b9e3.png)
![drawers_acacia_front_4](https://cloud.githubusercontent.com/assets/7751260/8016370/8cf17f3c-0bb0-11e5-897b-06b2cb15f0b7.png)

**Comment by Oddface** [comment]
Looks good! Just a little nitpicking. I don't know how you're doing the trim, but if it looks like it does here, it's going to look a little weird from a perspective, with the dark lines not really connecting and giving the right effect.
![2015-06-06_23 55 52](https://cloud.githubusercontent.com/assets/7591428/8021653/f4e7d170-0ca7-11e5-9147-83fc01711ceb.png)
I also feel like the reddish boxes, while aesthetically pleasing when the drawers are empty, makes the it look a little cluttered when there's something in them.

**Comment by lesdmark** [comment]
I see your point. Back to the drawing board. so to speak. Lol

**Comment by lesdmark** [comment]
Closing as I have most of it done at least for the version that's in Regrowth
