### ISSUE TITLE
Different versions of JSTR on FTB

### ISSUE THREAD

**Issue by MrCalhoun** [John-Smith-Modded/JSTR-1.7.x#113]
Hello,

the version (on github) is bigger than the version that you can get from the FTB Launcher.
The "FTB Launcher JS Texture Pack" got other textures than that one here.

For example:

The "FTB Launcher JS Pack" got an texture for the ME Storage Interface but not for all chisel 2 blocks.
The github JS Pack got no texture for the ME Storage Interface but for all chisel 2 blocks.

I think there are more than that example. Can someone merge the version and push it also to FTB?
Because github should be the only source for that and it would be a mess if already created texture and work lost.

**Comment by lesdmark** [comment]
if you open the zip and dump the assets folders in that you want it will update it. I unfortunately cannot update the FTB version for you. It should be updated soon though.

**Comment by MrCalhoun** [comment]
I tried it once but if I do that, MC will crash when I'm try to load the texture pack :(

**Comment by MrCalhoun** [comment]
Is there an easy way to get an ready to work texture pack from github?
If I download the zip I have to move so many files :(

**Comment by lesdmark** [comment]
Sorry for not responding again sooner but after you download the zip you want to unzip that folder then inside of each mods named folder is a folder called assets. The assets folder is the one you want to add to the top level of your zipped mod pack folder. when you open the zip file for the mod pack (which I recommend 7-zip for, it's free and easy to use) you literally just drag it into the mod folder where all you should see as far as folders is a folder called assets and some other files. Hope this helps
