### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by skwerlman** [John-Smith-Modded/JSTR-1.7.x#118]
What are the textures in this repo licensed under? 

The only license I could find is the old and vague [JSTP] license on the pack's original thread. Are the textures still licensed under that, or is there a more modern license anywhere?

Either way, the license should be easier to find than it currently is. (i.e. add a `LICENSE.md` file)

[JSTP]:http://www.minecraftforum.net/forums/mapping-and-modding/resource-packs/1223204-johnsmith-texture-pack-v9-7-32x-1-4-2

**Comment by Oddface** [comment]
Curious about this myself. There's some stuff on [this page](https://www.johnsmithlegacy.co.uk/johnsmith_tr.php), but It's a little unclear if these rules apply to this pack in particular.

**Comment by kardain** [comment]
It is reasonable to assume that the text contained on the second link is
the license itself. As the text references JSTR and directly links to this
repo (top links), the same licensing rules should be applicable.

It is fairly common for licenses to not be directly attributed to Creative
Commons, BSD, MIT, Apache, etc. but instead have a custom licence.
Basically, what is on that page is equivalent to a EULA found with
commercial (or non-commercial) software... At least that's how I read it.

Reviewing all available OSS licences, there is not a a direct match to what
JSC has typed up. CC comes close, but the odd non-distribute (with
exceptions) clause breaks it.

However, additional confirmation should be obtained.

**Comment by ScottKillen** [comment]
In a case like this, where there is no explicit license, should there ever be a controversy, individual contributors can assert their copyrights. (This was the issue behind Mojang's closing of the bukkit project...a major contributor was asserting his copyright.)

For the record, _I renounce my rights to anything I have contributed to this project, or will contribute in the future_. I leave it to others to determine what license governs the project as a whole.

**Comment by damonmensch** [comment]
Now I agree with Scott, and do the same as he, relinquishing rights to prior and future contributions, and always felt this way otherwise I never would have participated.

Also be mindful that regardless of whatever license attempted to be spilled to the project we are still limited by Github's ToS, most importantly section F.1.

"We claim no intellectual property rights over the material you provide to the Service. Your profile and materials uploaded remain yours. However, by setting your pages to be viewed publicly, you agree to allow others to view your Content. By setting your repositories to be viewed publicly, you agree to allow others to view and fork your repositories."

This alone pretty much removes the whole "this is mine copyrighted, you can't use it" scenario surrounding bucket.

**Comment by ScottKillen** [comment]
:+1:

**Comment by lesdmark** [comment]
Anything I contribute to the project then belongs to the project and no longer myself. I relinquish any rights I have to material I have contributed. I hate our copyright system for that very reason it stifles innovation.

**Comment by Oddface** [comment]
For the record, I am also renouncing any rights to my past and future contributions to this project. I doubt anyone would assert copyright in a project like this, but the OP is right, we need a license here to clear things up.

**Comment by ScottKillen** [comment]
If you all can come up with a license that fits: maybe one of the Creative Commons variants or even.[the Unlicense](http://unlicense.org) I don't mind setting up the License file or files and setting up clahub so that future contributors must agree to whatever licensing terms we setup here. 

We need to do our best to have unified consensus on license selection among as many prior contributors as possible. 

For an example of how clahub works take a look at the contributing file over at the MinecraftModArchive/dendrology repo.

**Comment by damonmensch** [comment]
Personally I agree with the unlicense, however this project originally was the work of a single man by himself. So on the spirit of that I think we should contact him and/or use a license that best follows what he wanted

**Comment by ScottKillen** [comment]
Indeed, which may or may not be possible. We could add a statement such as: "In the case of derivatives of John Smith's original textures, any restrictions of the original content supercede any rights granted by this license. "

**Comment by skwerlman** [comment]
I'm not sure such a clause is compatible with Creative Commons:

(From the summary of the CC-BY-NC-SA)
```
No additional restrictions — You may not apply legal terms or technological
measures that legally restrict others from doing anything the license
permits.
```

**Comment by damonmensch** [comment]
To which clause are you referring to @skwerlman?

**Comment by skwerlman** [comment]
The one suggested by @ScottKillen in the comment immediately before mine

**Comment by damonmensch** [comment]
Also if we copy the text in CC into our own license page and add that clause, it's no longer a CC license, and therefore that other line no longer applies.

Most people fall to realize that these licenses from CC, MIT, Apache, etc. never were intended to be used verbatim but as guidelines for non-lawyers and those who can't afford lawyers to more readily express what permissions they want to grant others for use in their content.

**Comment by ScottKillen** [comment]
I was not suggesting adding a clause to the license itself, but in the README adding some guidance for what content is covered and what is not.

I am not a lawyer, but I know that no matter what, we cannot specify a license for the original content. If we cannot contact JohnSmith himself then we will have to make such a stipulation on what ever licensing we decide on here.

**Comment by Oddface** [comment]
I think any license we decide on should have John Smith's terms in there, just to keep things simple. Figuring out what is derivative of his works and what is original seems like a real headache. There are also some Faithful 32 textures and derivatives in this repo, and those have terms against commercial use as well.

**Comment by ScottKillen** [comment]
I'm good with whatever you guys choose.

**Comment by lesdmark** [comment]
These are the issues that occur when someone disappears who created something and had a vague at best license to begin with. I'm not really particular as long as no one tries to make money off of it, or lock us out of the project. That would be the quickest way to kill the project

**Comment by goldbattle** [comment]
This is a mix between the original license and from what I have learned from Soartex.
Even through there are no default JSL textures in this repository, many of them stem from the default pack. This means that a CC and the such is not possible. Going from that, this was something I meant to get around to, but it slipped through the cracks.

* * *

John Smith Technician's Remix (JSTR) is a community pack built on top of the original John Smith Legacy pack. Bear in mind, that a whole community work is involved in this project and these rules are to protect such work. As such, we have rules that as a user, you must agree to comply with when using our work. You can find these rules below:

1. No money can be made from distribution of the pack and individual textures
2. Public redistribution of JSTR pack outside the root domains is strictly prohibited. Allowed domains are:
   - http://www.johnsmithlegacy.co.uk/
   - http://js-legacy.net/
3. Public redistribution of JSTR from third party websites and platforms is strictly prohibited.
4. Contributors retain all copyright over their textures and are free to use their work else where
5. The hosting public mixpacks is discourage, please provide a patch that is layered on top of the default download.
6. Third party projects; meaning non-related minecraft resourcepack projects, using our textures are not allowed
6. The JSTR community retains the right to redistribute any texture submitted and have the ability to grant or deny permission for requests on distribution.

This license solely applies to John Smith Technician's Remix.
© 2012-2015 John Smith Technician's Remix Community. All rights reserved.

* * *

Here you go. Let me know what you think.

**Comment by damonmensch** [comment]
I would recommend adding Github to the list of distributable locations. This way, if decided to, we can just release directly from Github, which I have seen other projects doing. Also creates less of a headache if someone decides to make the pack themselves directly from the repository.

**Comment by goldbattle** [comment]
This has been added to the new release, please check #122 for updates.
