### ISSUE TITLE
Experience obelisk "+" and "-" signs on interface won't show up

### ISSUE THREAD

**Issue by Metal-Mighty** [John-Smith-Modded/JSTR-1.7.x#119]
"+", "++" and "+++" and their negative counterparts aren't shown on the Experience Obelisk interface (JSTR Universal 1.7.x)

![2015-08-01_17 57 18](https://cloud.githubusercontent.com/assets/5247527/9023745/0a048da0-3877-11e5-9d8b-de94b49e1c1e.png)
![2015-08-01_17 58 48](https://cloud.githubusercontent.com/assets/5247527/9023744/0a046898-3877-11e5-9def-6274e7833404.png)

**Comment by Oddface** [comment]
Fixed. Just a sheet of gui icons and buttons that hadn't been updated. Thanks for the report!
