### ISSUE TITLE
Base pack CTM error

### ISSUE THREAD

**Issue by ScottKillen** [John-Smith-Modded/JSTR-1.7.x#122]
There is an error ctm textures for buttons in the 1.7.10 base pack. I can make a patch to fix it...Is it appropriate to incorporate it here, or is it better to release as a patch, like the legacy-patch, or the 64x pack?

Comments please!

**Comment by lesdmark** [comment]
I hate that we cannot access the base pack sometimes. I am guessing the best thing to do would be to try to contact Jim Stone I think it is and have him fix it. BTW slightly off topic Scott but is there any way you can make me a rainbow sapling texture for Chromaticraft in the pack? I would appreciate it.

**Comment by ScottKillen** [comment]
@lesdmark I got that last part before your edit. :grinning: 

I'll see what I can do.

I'll also try and get ahold of Jim Stone...

**Comment by ScottKillen** [comment]
OK.

I have a message in to Jim Stone.

I would love someday to get a history and an understanding as to how Jim Stone came about taking over for John Smith. and why we use his pack and don't maintain the base ourselves...

Not saying we should...just curious as to how all of this got the way it is.

**Comment by goldbattle** [comment]
You can always add it to the https://github.com/John-Smith-Modded/JSTR-Overwrites repo if it is JSTR specific.

**Comment by Greenhawk837** [comment]
Yeah, to be honest it's a joke how the base pack has ended up, it's why I haven't been around here for some time, this pack has just lost it's structure, meaning that it also lost a lot of it's users. 

I downloaded Jimstone's pack the other day and well yeah... it's not bad and all, but it's so not John Smith. Not at all

**Comment by ScottKillen** [comment]
@goldbattle It is a problem with the base JS pack

**Comment by lesdmark** [comment]
Is there a way we can create a more try to the original JS base pack and base ours off of that instead? I try to keep what I make true to the original, but sometimes it's hard. I have to use an overlay pack I made in addition to the JSTR pack to give me back the vanilla textures as I don't care for some of the changes made to the base.

**Comment by ScottKillen** [comment]
I'm with @lesdmark ...

I emailed Jim Stone and explained that I was a contributor to JSTR..and even told him how to fix the problem...

He said that the problem was only with 1.7.10 and:

```
As I only look after Vanilla Resource Pack and have little involvement with
the modded I cannot update the base pack for the modded game.

Maybe contact the [JSTR team] and see it they will sort out the base pack issues.
```

Disappointingly, Jim only read the subject line of my message and replied... **_the fix was in the message!_**

After this reply, I am all for us branching out with our own base pack...what needs to be done?

[email text](https://gist.github.com/ScottKillen/cd577de3f9bd4a7d6298)

**Comment by ScottKillen** [comment]
Well...I spoke too soon...

From Jim Stone:

```
Sorry I didn't realise, I've updated the pack to fix the buttons and also backdated
all the updated textures from the later packs, like horses and many others.
```

So...if we update the base, this should be good to go...

**Comment by goldbattle** [comment]
Currently working on updates, everything seemed to be working well with FTB infinity. I will post with download links when I have them. I moved the base to the vanilla version `v1.2.22` which included the August 30th updates.

**Comment by goldbattle** [comment]
Here are the two files:
* Patch pack: http://minecraft.curseforge.com/texture-packs/223328-john-smith-legacy-modded/files/2255920
* Main pack: http://minecraft.curseforge.com/texture-packs/223328-john-smith-legacy-modded/files/2255922

**Comment by lesdmark** [comment]
Since we resolved this, I am closing it.
