### ISSUE TITLE
EnderIO 2.3 GUI Fixes?

### ISSUE THREAD

**Issue by spannerman79** [John-Smith-Modded/JSTR-1.7.x#125]
As you can see the layout has changed with the Farming Station (and possible others)

![2015-09-08_17 59 16](https://cloud.githubusercontent.com/assets/7542384/9729751/efcca2a0-5654-11e5-8552-e2788c669485.png)

I've red boxed the additional areas for the Faming Station - I haven't gone through the rest of EnderIO changes yet but I'm sure there is more.

Related: Issue #10 User: @Kayot

Edit: I missed the Bonemeal section at the top - my bad

**Comment by lesdmark** [comment]
I started working on the GUI changes. this means it is no longer correct for 2.2 so anyone still using it will want to not update to these textures

**Comment by lesdmark** [comment]
Just about done correcting the existing GUI's. Then to add the missing ones.

**Comment by spannerman79** [comment]
Thank you for your time and effort for this.  You have no idea how "weird" it looked

:+1:

**Comment by lesdmark** [comment]
No problem

**Comment by lesdmark** [comment]
What uses the textures from externalconduitconnection I need to see how they are used to know how to go about retexturing it. I am working on the rest as I write this.

**Comment by lesdmark** [comment]
I think this has been resolved for the most part. so closing it now
