### ISSUE TITLE
Pack update?

### ISSUE THREAD

**Issue by ArfourFoulkesayke** [John-Smith-Modded/JSTR-1.7.x#126]
It's been rather quiet here lately, but nonetheless it has also been quite a while since the last update.

The version of the pack on the website is from May 30th. Could someone do an update, please?

I have come across a few missing textures and stuff since our latest server update and want to see if they are fixed already before doing a comission myself. I guess it's mostly just rearranged files by the modmakers but who knows, right?

**Comment by lesdmark** [comment]
I think right now I am the only one doing anything with the pack and I cannot push new versions. Hopefully someone who can will see this

**Comment by ScottKillen** [comment]
I think thatr @goldbattle is the only one who can afaik

**Comment by Glowstrontium** [comment]
Hmm, I should be able to upload a new version to Curse, but honestly I have been out of the loop around here for so long that I'm not sure what needs to be done.  I could compile a .zip from the repository, but someone will need to make a changelog.  At some point soon, I'll try and do an audit of what we have and see what is broken or needs updating.

**Comment by goldbattle** [comment]
Have been busy with classes, will try to get one done this weekend, I think the last one I did was back in September.

**Comment by goldbattle** [comment]
Should be updated now.

**Comment by lesdmark** [comment]
Since this has been done I'm closing it.
