### ISSUE TITLE
AE2 Molecular Assembler texture

### ISSUE THREAD

**Issue by Hazmatik** [John-Smith-Modded/JSTR-1.7.x#127]
The frame is rendering but the internal part of it is not.

![2015-10-23_10 15 50](https://cloud.githubusercontent.com/assets/8119393/10695108/f911bdf8-796f-11e5-9505-293274c54536.png)

**Comment by lesdmark** [comment]
Is this rev 2 or rev 3?

**Comment by lesdmark** [comment]
Should be fixed now. Reopen the issue if it isn't
