### ISSUE TITLE
Wood Stuff Support

### ISSUE THREAD

**Issue by damonmensch** [John-Smith-Modded/JSTR-1.7.x#133]
Right now I'm working on adding support for Wood Stuff. It's a mod that adds crafting tables, bookshelves, and wood chests for wood added to your game, other than the standard oak.

I had no problem adding the chests and bookshelves for JSTR, Crafting Tables on the other hand are proving to be more of a challenge. I think I finally settled on a wall side I can live with. Our usual "carry bar" seemed too out of place for the plank blocks.

This mod uses overlays of it's block over the other mod's plank texture.

![woodstuff default](https://cloud.githubusercontent.com/assets/1498614/11089096/035a1dae-8835-11e5-81a3-e22698131746.png)
That's Default Wood Stuff Mod with our existing plank textures. (Larch, Ethereal, Greatwood)

![woodstuff jstr](https://cloud.githubusercontent.com/assets/1498614/11089108/27e182ca-8835-11e5-8266-7e1cb37e37dd.png)
Same blocks with my alterations.

**Comment by damonmensch** [comment]
I couldn't think of anything else to put on the side so I left it blank, we don't seem to have many alternate side walls for crafting tables. The tools for the front I pulled from our Natura set.

**Comment by Oddface** [comment]
Looks good! I think this is really the only way to do this mod with how our plank textures look.

**Comment by ScottKillen** [comment]
:+1:

**Comment by damonmensch** [comment]
#135
