### ISSUE TITLE
Loamy Dirt/Grass

### ISSUE THREAD

**Issue by damonmensch** [John-Smith-Modded/JSTR-1.7.x#134]
I would like to recommend we make the loamy dirt, the same tint we make the dirt portion of the loamy grass. I only suggest this to make it appear more seamless. Otherwise we get something like this...
![loamy dirt](https://cloud.githubusercontent.com/assets/1498614/11089552/ae5a6aee-8838-11e5-8b89-2225d4e30698.png)

I know the original modder didn't take this into consideration when he made the textures, put personally I think it's an eyesore when it stands out that much.

**Comment by ScottKillen** [comment]
From http://biomesoplenty.wikia.com/wiki/Loamy_Dirt: 

_Loamy dirt looks and functions like regular dirt, but is subtly darker in color. It can be found in some swampy or other moist biomes._

-and-

http://biomesoplenty.wikia.com/wiki/Loamy_Grass:

_Loamy Grass is a block that functions the same as a regular grass block, but has a darker texture._

I would agree that the green hue seems wrong. The texture should be *slightly* darker than normal grass/dirt textures

**Comment by Oddface** [comment]
![dirt_loamy](https://cloud.githubusercontent.com/assets/7591428/11092189/9632178e-8881-11e5-98b1-2df69abe5dff.png)
![grass_loamy_side](https://cloud.githubusercontent.com/assets/7591428/11092192/98067f8c-8881-11e5-875a-67e5776dffcf.png)
These are the textures in the repo. They're the same color, but in the game they look different for some reason.

**Comment by ScottKillen** [comment]
Because the mod applies biome shading to the grass--which explains the green tint.

This is not something that can be fixed in the resource pack.

**Comment by Oddface** [comment]
It's supposed to just apply to the grass overlay and not the whole block, right? Seems like a bug.

**Comment by ScottKillen** [comment]
Yes, The mod is applying it to the whole texture.

**Comment by ScottKillen** [comment]
This should probably be reported over at [the BoP repository](https://github.com/Glitchfiend/BiomesOPlenty).

**Comment by Oddface** [comment]
I'll just close this then.

**Comment by lesdmark** [comment]
That's weird mine didn't do it when I tested it.

**Comment by lesdmark** [comment]
Here is a screenshot from my game using BOP 2.1.0.1396
![2015-11-11_22 10 05](https://cloud.githubusercontent.com/assets/7751260/11109694/37b2795c-88c1-11e5-81e0-04ec17638f82.png)

**Comment by ScottKillen** [comment]
I thin the textures were deisgned for the biome you are in. Note the first screenshot was from a Coniferous Forest...not the place that Loamy dirt/grass is normally found.
