### ISSUE TITLE
Chisel Mod

### ISSUE THREAD

**Issue by calmcacil** [John-Smith-Modded/JSTR-1.7.x#14]
I realize this might be asking for much, but are there any plans of adding chisel support? Currently one of my favorite mods for building things with since you get such variety out of several types of blocks, but i imagine the same variety might make it a little hard to support in terms of making custom textures.

**Comment by Oddface** [comment]
I anyone working on the marble textures? @Greenhawk837 posted some stuff, but it also looked like @Satellence had some marble textures in some screenshots he posted.

**Comment by Greenhawk837** [comment]
There were a couple marble textures that I was working on before, but I've ended up just working on 64x textures.

**Comment by lesdmark** [comment]
The one thing I notice about this mod is more textures being continuously added. It would take someone working on this quite a bit to get it all done. I am closing this for now as no one has worked on it or is working on it in quite some time. If someone starts to actively work on it then we can reopen the thread.
