### ISSUE TITLE
Forestry chest textures broken

### ISSUE THREAD

**Issue by Qohelethh** [John-Smith-Modded/JSTR-1.7.x#148]
The latest version of Forestry replaces the multiple textures for the apiarists and other chests with a single unified chest texture, so Forestry chests are now un-textured.

**Comment by damonmensch** [comment]
You are referring to forestry v4.2.9 correct?

**Comment by Oddface** [comment]
We really are overdue for an update to the pack. I did this back in November: https://github.com/John-Smith-Modded/JSTR-1.7.x/commit/e168854581d28ec09c29023f6918c73b1b5756fb
@goldbattle

**Comment by Qohelethh** [comment]
@damonmensch Yes sir. I see that @Oddface has already done this. Thanks!
