### ISSUE TITLE
Ae2 Rv1?

### ISSUE THREAD

**Issue by calmcacil** [John-Smith-Modded/JSTR-1.7.x#15]
anyone working on updating for AE2 Rv1 some interfaces changed.

**Comment by lesdmark** [comment]
I'm going to take a look at these and see what I can do

**Comment by goldbattle** [comment]
This has been fixed on https://github.com/John-Smith-Modded/JSTR-1.7.x/commit/4479634dee800ef0761d446d886715156ff15424. It will be included in the next update.
