### ISSUE TITLE
Problem with info screens

### ISSUE THREAD

**Issue by Darktotaled** [John-Smith-Modded/JSTR-1.7.x#192]
Im having this problem when im using the texture pack where infoboxes like the one from Calculator(Info Calculator Item) are transparent and dark, making it hard to read, at least for me. Is there any workaround for that?
As you can see below, there is a image of the same infobox with and without the texturepack active. Currently using latest.

![WhatsApp Image 2023-11-27 at 23 09 10](https://github.com/John-Smith-Modded/JSTR-Modded-1.7.x/assets/15343248/889785c0-b7b6-4c26-935c-5c2567b6847b)
![WhatsApp Image 2023-11-27 at 22 57 26](https://github.com/John-Smith-Modded/JSTR-Modded-1.7.x/assets/15343248/8c6dd863-5bff-44a4-b0f2-a6a35db4a94b)

**Comment by ScottKillen** [comment]
This is what prompted me to make [Nellik's Guis](https://www.curseforge.com/minecraft/texture-packs/nelliks-highdef-guis).

I don't know of a fix, so I routinely use that pack as an overlay, or strip out all of the GUIs from JohnSmith.

**Comment by Darktotaled** [comment]
I'll try that out. Thanks.

On another note, as most screens from JS are transparent and dark colored, wouldnt changing the text color to something brighter alleviate the issue?

**Comment by Darktotaled** [comment]
welp, it didnt work with either versions of nellik gui, ingame only and the normal version.
![image](https://github.com/John-Smith-Modded/JSTR-Modded-1.7.x/assets/15343248/09ec6fa6-fc4e-4993-afb6-21d090adf892)

**Comment by ScottKillen** [comment]
You've got to make sure that Nellik appears in the resource pack list **before** JohnSmith.

If that doesn't work, please post a screenshot of your resource pack selection screen.

**Comment by Darktotaled** [comment]
It was on top.
Nellik
JS smooth
JS Modded (latest)

As you saw in the screenshot, it changed all the buttons that JS normally changes but the screen itself is still transparent

**Comment by Darktotaled** [comment]
![Screenshot_5](https://github.com/John-Smith-Modded/JSTR-Modded-1.7.x/assets/15343248/dce24ff1-841c-4293-af2d-2313458ae604)
![Screenshot_3](https://github.com/John-Smith-Modded/JSTR-Modded-1.7.x/assets/15343248/70b39fb3-572d-4d30-a307-e926e2561ab4)
![Screenshot_4](https://github.com/John-Smith-Modded/JSTR-Modded-1.7.x/assets/15343248/fc15ec0f-29a0-4a68-9f8e-e12a2e32abf6)

the resourcepack order and the modlist, if you think its relevant

**Comment by Darktotaled** [comment]
i removed the smooth patch, after i sent the screenshot. didnt notice it was already included.

**Comment by ScottKillen** [comment]
If Nellik does not support the mod in question, you will still see JohnSmith's GUI. Try removing the GUI from John Smith.

**Comment by Darktotaled** [comment]
![image](https://github.com/John-Smith-Modded/JSTR-Modded-1.7.x/assets/15343248/22bb8aa2-9d24-4e52-a329-1c577b9706a6)

the problem is the window itself. As you can see its using the default grey and only the buttons changed to nellik's. When nellik is above JS, it changes only the buttons but not the window, so JS is changing the window somewhere and making it dark and transparent.
So pretty much, its something JS supports/changes, but not nellik

**Comment by Darktotaled** [comment]
Im looking through the files inside the resourcepack and nei's background is blank
![image](https://github.com/John-Smith-Modded/JSTR-Modded-1.7.x/assets/15343248/4c2e468e-ce05-4b7b-a3a9-e39409fe478c)
the two screens that i know that have the dark transparent background,which could be just a invisible background, are the info screen from info calculator, which requires nei to work and actually additions item info screen

**Comment by Darktotaled** [comment]
I got it
![image](https://github.com/John-Smith-Modded/JSTR-Modded-1.7.x/assets/15343248/814c3fa9-3de6-4e8e-87b9-0298ab0597b5)

**Comment by Darktotaled** [comment]
i edited the png in paint and rebooted minecraft. its exactly nei recipebg
