### ISSUE TITLE
Plank revamp discussion

### ISSUE THREAD

**Issue by Oddface** [John-Smith-Modded/JSTR-1.7.x#24]
Planks are sorta weird right now. They're inconsistent and it damages the cohesiveness of the pack. I think we need to decide on one style of doing the planks and stick with it. For a while now it's been the oak texture from the original John Smith, but personally I don't really like it. It's great as one of the 6 types of wood in vanilla Legacy, but as a base for every plank texture in modded Minecraft, I just think it's a little too stylized, too grimy. I think @Satellence is onto something with his work on Chisel in the 1.6 repo. They're a little smoother and more stylistically flexible while still keeping with the John Smith style. 

![](https://raw.githubusercontent.com/John-Smith-Modded/JSTR-1.6.x/master/Chisel/assets/chisel/textures/blocks/planks-oak/blinds.png)
This is the blinds variation, which would be my choice for a new standard. 

Those are just my two cents. This would obviously be a sweeping, somewhat controversial change for the pack, so I think it's important that we talk about it. What do you guys think? How do you like your planks?

**Comment by damonmensch** [comment]
Personally I feel we should have a different style in for each of the vanilla planks, then have the mods ones be variations of those.

Example have Ebony from forestry match the style of jungle, but magic from BoP match birch, and maybe cherry from BoP be like spruce.

**Comment by lesdmark** [comment]
The biggest problem I see with having a bunch of different ones is lets say you make cherry look like birch but the person wants cherry to look like oak. I think a unified type for all the woods might be best and then for variety people can use chisel 2 to change it up.

**Comment by damonmensch** [comment]
In that case what I could recommend is to maybe have the mod ones done in alt styles so people can have overwrites if they prefer one over the other

**Comment by Greenhawk837** [comment]
The average user of this pack isn't going to be using overwrites. I also agree that a unified setup is both easier and better

**Comment by Greenhawk837** [comment]
I'm just wondering why does the colour of the oak planks now mimic default Minecraft? personally I think they look so out of place in JS. I just never noticed because I've always used my own vanilla pack.

**Comment by Oddface** [comment]
The changes to the vanilla planks are due to the Chisel support, which pretty much switches up how everything looks. The oak and birch are brand and look more vanilla like, and the jungle planks look pretty much like oak used to look. The spruce mostly looks like it used to, only a little brighter. I'm making some tweaks to the Chisel stuff right now, and considering some more drastic changes. Staying completely true to the original John Smith planks doesn't really make sense because they all have very similar colors, but I don't really love how it looks now either. Any thoughts on this?

**Comment by Greenhawk837** [comment]
![planks_acacia](https://cloud.githubusercontent.com/assets/6283808/5937928/9443a186-a745-11e4-9b96-73b1b742a5bf.png) ![planks_big_oak](https://cloud.githubusercontent.com/assets/6283808/5937929/94466696-a745-11e4-8a00-306f8bb56581.png) ![planks_birch](https://cloud.githubusercontent.com/assets/6283808/5937930/944a3140-a745-11e4-8a9a-54d7cd95ed8e.png)
![planks_jungle](https://cloud.githubusercontent.com/assets/6283808/5937932/944f2042-a745-11e4-9def-52adc2584dd4.png) ![planks_oak](https://cloud.githubusercontent.com/assets/6283808/5937931/944e12a6-a745-11e4-93fc-abaf411ea06f.png) ![planks_spruce](https://cloud.githubusercontent.com/assets/6283808/5937935/9cbee276-a745-11e4-978a-911ce1421721.png)

these are the original JSTR planks

**Comment by Oddface** [comment]
Right. I was talking about the Legacy style planks that were used in JSTR 1.6 and 1.7. This is how they were done in 1.4 and 1.5, for the record.
![oak](https://cloud.githubusercontent.com/assets/7591428/5938130/6caeb77a-a6f8-11e4-816c-eab2c1708ab1.png)
![spruce](https://cloud.githubusercontent.com/assets/7591428/5938131/6caf511c-a6f8-11e4-966f-5ac4dd34eb15.png)
![jungle](https://cloud.githubusercontent.com/assets/7591428/5938132/6cb365c2-a6f8-11e4-8b72-76e56ca52fa8.png)
![birch](https://cloud.githubusercontent.com/assets/7591428/5938133/6cb74a52-a6f8-11e4-95ba-3cbd80e6a5f5.png)

**Comment by Satellence** [comment]
(Sorry for my English)
To make difference between chiseled wooden planks, i make a new texture in 1.6.4 Chisel mod.
I prefer more clearly and contrast textures. So, my variant is best for me. Maybe, it will be better as default in texture pack.
![planks_jungle](https://cloud.githubusercontent.com/assets/1390832/5938297/a062b2c6-a70a-11e4-8a2f-e13984234042.png)
![planks_oak](https://cloud.githubusercontent.com/assets/1390832/5938299/a0654522-a70a-11e4-860e-345ec8cd80ed.png)
![planks_spruce](https://cloud.githubusercontent.com/assets/1390832/5938298/a0631e5a-a70a-11e4-8d6f-7fc2265b6dcf.png)
![planks_birch](https://cloud.githubusercontent.com/assets/1390832/5938296/a061dbd0-a70a-11e4-9a86-c7252414fe8e.png)

**Comment by ScottKillen** [comment]
@Satellence These are nice.

**Comment by Oddface** [comment]
Here's what I'm working on. It's kind of a remix of the Chisel stuff Satellence made with acacia and dark oak added. I tried to be faithful to both the Legacy planks and older JSTR stuff, as well as the default look. I'm showcasing the blinds variations here, but I've done all the Chisel stuff (with some other tweaks).

oak
![blinds](https://cloud.githubusercontent.com/assets/7591428/5944973/8c8f2db2-a72b-11e4-9821-1ced2f3f3fde.png)
birch
![blinds](https://cloud.githubusercontent.com/assets/7591428/5944985/99044b04-a72b-11e4-8ca2-a78577b8eb39.png)
spruce
![blinds](https://cloud.githubusercontent.com/assets/7591428/5944996/a3b42bc8-a72b-11e4-9459-8625271805b4.png)
jungle
![blinds](https://cloud.githubusercontent.com/assets/7591428/5945018/bf3f4b98-a72b-11e4-8851-7809d76d0b82.png)
acacia
![blinds](https://cloud.githubusercontent.com/assets/7591428/5945030/caa75dd6-a72b-11e4-97d1-151204ce3f2a.png)
dark oak
![blinds](https://cloud.githubusercontent.com/assets/7591428/5945040/dbe937c2-a72b-11e4-8f84-646e140a257e.png)

**Comment by lesdmark** [comment]
So the planks greenhawk has are the way I would say they should all look. and then the ones oddface is adding for chisel look like they work together. It keeps everything simple and unified and makes adding new wood planks easier.

**Comment by Oddface** [comment]
Hm, I don't think the original JSTR planks really fit in well with the new chisel ones. They look very "soft" by comparison. It's just a different style, from a way older version of the pack. It's pretty obvious that John Smith means very different things to different people since it changed so much over the years. We're not all going to be 100% happy no matter what we choose, but we need to pick a direction and stick with it.

**Comment by lesdmark** [comment]
So would the replacement for the main ones look like the ones you have above with the lines in them like the old ones? I would like to see that. I admit I just loaded up the ones you have the blinds variety and i like them,  could we see them with the lines like the originals? The ones Satellence has just look too modern to me. JSTR to me has a feel somewhere between Medieval and Victorian with a bit of Steampunk Kind of a classic JRPG feel.

**Comment by Greenhawk837** [comment]
yeah the blinds variety looks really nice, but I do find that the oak planks are still a touch to light IMO

**Comment by Oddface** [comment]
Yeah, the blinds variety is what I'm thinking for default. It's nice and simple and works for all types of builds while still looking like John Smith. I'll try to tweak the oak a bit.

**Comment by damonmensch** [comment]
I like the new blinds it's a cruise between the old classic oak, and a newer design. Should we get a couple variations for mcpatcher support like the original oak planks has?

**Comment by Satellence** [comment]
Screenshots for comparison

![2015-01-29_15 05 25](https://cloud.githubusercontent.com/assets/1390832/5956591/72024f52-a7c0-11e4-8070-ca5134f72d0c.png)
![2015-01-29_15 06 07](https://cloud.githubusercontent.com/assets/1390832/5956592/721aa156-a7c0-11e4-8e8b-fb71a1eb73a0.png)
![2015-01-29_15 06 20](https://cloud.githubusercontent.com/assets/1390832/5956593/722d259c-a7c0-11e4-9ffa-7962d7399589.png)
![2015-01-29_15 06 30](https://cloud.githubusercontent.com/assets/1390832/5956594/722eff48-a7c0-11e4-9d63-ca822ef7262f.png)

**Comment by Oddface** [comment]
The oak and old oak are incorrect in the screenshot for my version.

**Comment by Satellence** [comment]
I'm sorry. Fixed.

**Comment by Oddface** [comment]
Alright. I've made the oak a bit darker, pretty close to the Legacy version. I also tweaked the acacia color a little bit. I've included the "short" and "chaotic variations as well, which could be used when making mod planks for a little bit of variety.

oak
![blinds](https://cloud.githubusercontent.com/assets/7591428/5957508/bf9523f8-a7ba-11e4-954d-4a8101c55a42.png) ![short](https://cloud.githubusercontent.com/assets/7591428/5957517/cde2c622-a7ba-11e4-8be5-c8760ca808f5.png) ![chaotic](https://cloud.githubusercontent.com/assets/7591428/5957519/d43609c6-a7ba-11e4-9b91-380f38ff73e1.png)

birch
![blinds](https://cloud.githubusercontent.com/assets/7591428/5957525/ea082fae-a7ba-11e4-967d-726c625b4d4d.png) ![short](https://cloud.githubusercontent.com/assets/7591428/5957531/fb2dac78-a7ba-11e4-80ae-cc63de317073.png) ![chaotic](https://cloud.githubusercontent.com/assets/7591428/5957526/f045967c-a7ba-11e4-99c3-03b1f7f18e58.png) 

spruce
![blinds](https://cloud.githubusercontent.com/assets/7591428/5957540/1984f348-a7bb-11e4-9f8e-93a38dbe02a4.png) ![short](https://cloud.githubusercontent.com/assets/7591428/5957543/1f748d18-a7bb-11e4-8dcf-874f78f943a6.png) ![chaotic](https://cloud.githubusercontent.com/assets/7591428/5957554/36393530-a7bb-11e4-89f8-05a520c9bd4f.png)

jungle
![blinds](https://cloud.githubusercontent.com/assets/7591428/5957558/4ae4a2b2-a7bb-11e4-84ab-7fa23fa70a7f.png) ![short](https://cloud.githubusercontent.com/assets/7591428/5957559/5286babe-a7bb-11e4-90f8-b4b3c07d379a.png) ![chaotic](https://cloud.githubusercontent.com/assets/7591428/5957562/63429544-a7bb-11e4-90bd-1773dda74327.png)

acacia
![blinds](https://cloud.githubusercontent.com/assets/7591428/5957576/8da9701e-a7bb-11e4-9c7e-f7d9e54078d5.png) ![short](https://cloud.githubusercontent.com/assets/7591428/5957581/9308a732-a7bb-11e4-9339-d3807c55bb06.png) ![chaotic](https://cloud.githubusercontent.com/assets/7591428/5957585/9b20dcbe-a7bb-11e4-9a2d-279a8a103ff1.png)

dark oak
![blinds](https://cloud.githubusercontent.com/assets/7591428/5957593/acd961ba-a7bb-11e4-8c6d-6579043e7eb5.png) ![short](https://cloud.githubusercontent.com/assets/7591428/5957594/b1413eb2-a7bb-11e4-9574-c3f3ac99def9.png) ![chaotic](https://cloud.githubusercontent.com/assets/7591428/5957597/b9ea2984-a7bb-11e4-81b9-87bb91e4158c.png)

**Comment by ScottKillen** [comment]
These are very nice, Odd.

**Comment by ScottKillen** [comment]
I am looking closely at the resolution to this discussion so I can do textures for my Ancient Trees mod.

**Comment by ScottKillen** [comment]
@Satellence what are those giant stone blocks in the images? retextured stone?

**Comment by lesdmark** [comment]
Those are I think pretty close to perfect and a good match for the pack. I think those should be what we go with

**Comment by Satellence** [comment]
@ScottKillen there in default JSL pack for 1.8.1

**Comment by ScottKillen** [comment]
Thanks!

**Comment by Oddface** [comment]
So... do we have an agreement here? I've made a couple more minor tweaks and I think it's good to go.
Changed a few pixels on the acacia and birch to look a bit smoother.
![blinds](https://cloud.githubusercontent.com/assets/7591428/5965865/c2533d4c-a7ff-11e4-95d4-42f66e5bb7fb.png) ![blinds](https://cloud.githubusercontent.com/assets/7591428/5965940/62e3053a-a800-11e4-8a5f-09a1fe15fb32.png)
Made the gaps in the jungle wood a tiny bit brighter.
![blinds](https://cloud.githubusercontent.com/assets/7591428/5965897/1347ae40-a800-11e4-9ad5-73dc34fd4b21.png)

**Comment by ScottKillen** [comment]
I like these. :+1:

**Comment by lesdmark** [comment]
I second that :)

**Comment by Greenhawk837** [comment]
Looks good to me!

**Comment by lesdmark** [comment]
So is anyone going to tackle the BoP woods if not I can most likely do it.

**Comment by lesdmark** [comment]
I guess we can do the BoP , Thaumcraft, Forestry, Binne's mods now. More wood yeah!

**Comment by Oddface** [comment]
Alright the Chisel update is committed! Now for the mod planks, I did some stuff for BoP in this style a while back. I'll look over it and see what's worth posting. I'm sorta planked out at the moment, so if some other people could do the heavy lifting with the mod stuff, that would be great :+1:

**Comment by lesdmark** [comment]
I can work on them once you post what you have.

**Comment by Oddface** [comment]
Yes, but I also think you can throw in a "short" variation here and there, maybe "chaotic" too? We haven't really discussed the "rules" so to speak. I think for a normal plank block the planks need to be straight, horizontally oriented and have a vertical element, either short planks, blinds or both. Exceptions can be made if the default texture calls for it (the vertical BoP palm planks for example). Anyone else have thoughts on this?

**Comment by lesdmark** [comment]
That's exactly what I was thinking of doing. mixing up between them for a bit of variety.

**Comment by Oddface** [comment]
It's pretty much how they do it on the Soartex pack. There's the standard texture that's used more than the others, but there's still room for some variation.

**Comment by Oddface** [comment]
I've posted my BoP stuff now.

**Comment by damonmensch** [comment]
Aren't some of the regular (default) planks vertical? Perhaps those should be vertical here as well

**Comment by Oddface** [comment]
I did mention that there are exceptions. When the default texture is different from the vanilla minecraft planks, our textures should have the same kind of difference, like the vertical palm tree and the uneven redwood from BoP and the two-toned redwood from natura.

**Comment by Oddface** [comment]
If you're working on something for this overhaul, post about it here so there's no duplicate work going on. I'm currently working on Natura.

**Comment by damonmensch** [comment]
I'm working on BoP

**Comment by damonmensch** [comment]
I based the BoP I did off of the color scheme on the original defaults in the mod.

![plank_ethereal](https://cloud.githubusercontent.com/assets/1498614/5978702/c9a66342-a86f-11e4-9c00-136a1de08311.png) Ethereal
![plank_fir](https://cloud.githubusercontent.com/assets/1498614/5978711/d232bfe2-a86f-11e4-99f2-9e65c1137a24.png) Fir
![plank_hell_bark](https://cloud.githubusercontent.com/assets/1498614/5978713/d6d8f8c2-a86f-11e4-8514-5ba9e3d7bd61.png) Hell Bark
![plank_jacaranda](https://cloud.githubusercontent.com/assets/1498614/5978714/dbf3a9ba-a86f-11e4-92d0-02fad14716df.png) Jacaranda
![plank_magic](https://cloud.githubusercontent.com/assets/1498614/5978722/e30b75de-a86f-11e4-96af-ffd0a743af4e.png) Magic
![plank_mahogany](https://cloud.githubusercontent.com/assets/1498614/5978735/f880cd1a-a86f-11e4-8c44-36a196e6d80f.png) Mahogany
![plank_palm](https://cloud.githubusercontent.com/assets/1498614/5978739/fdee9796-a86f-11e4-9bf3-37307a307cf7.png) Palm
![plank_pine](https://cloud.githubusercontent.com/assets/1498614/5978745/022ef2ec-a870-11e4-8ff0-6a5477be01c0.png) Pine
![plank_sacredoak](https://cloud.githubusercontent.com/assets/1498614/5978748/059458aa-a870-11e4-9c0d-dbe43b524a44.png) Sacred Oak
![plank_willow](https://cloud.githubusercontent.com/assets/1498614/5978750/0965a3da-a870-11e4-8fa4-7bd0dd7620c3.png) Willow

From what I can tell Hell Park appears to be nothing more than a version of Birch that has reddish undertones mixed in, basically birch with just a noise filter on it. And Sacred Oak was a wide plnak version of normal oak.

There's also an inconsistency with Magic Wood. The log shows the heart as a magenta hue, yet it's planks are a light blue/teal hue. That's how it's been for a long time. Mimicking default magic planks are an indigo/teal.

Also looking into the mod, Holy no longer appears to exist, so that should probably be committed out.

**Comment by Oddface** [comment]
These look good, but you don't need to stick so strictly to the default colors. John Smith planks are generally a little more subdued and darker than default. If the default color works, then that's fine, but don't be afraid to experiment with saturation, hues and brightness to find something that could fit the pack better.

**Comment by damonmensch** [comment]
Only one of those I feel doesn't fit properly would be magic, I'll play with that one a bit more and see what I come up with. The others are all similar to the original but not exact. Personally I love how the fir came out. Think I'll play with hell bark a bit more as well.

**Comment by Oddface** [comment]
Here's an idea how you can do the hell bark a little more subtly. It's sometimes good to look at other texture packs for inspiration, not just the default textures.
![](https://raw.githubusercontent.com/Soartex-Modded/Modded-1.7.x/master/Biomes_O_Plenty/assets/biomesoplenty/textures/blocks/plank_hell_bark.png)

**Comment by damonmensch** [comment]
Ok since I personally liked the colors found in our previous version of Magic Planks I brought them back, only a touch darker and more subtle between the blue and green, in my opinion, and I also made hell bark more reddish in tone and more subtle.

![plank_magic](https://cloud.githubusercontent.com/assets/1498614/5988433/0c4978ec-a92e-11e4-9002-01c521e22a88.png)
![plank_hell_bark](https://cloud.githubusercontent.com/assets/1498614/5988438/3107bc66-a92e-11e4-83c3-10b83082c32c.png)

**Comment by damonmensch** [comment]
I'm having trouble getting the Greatwood and Silverwood planks from Thaumcraft somewhere I like, so I'll pass it on to someone else. Going to focus more on the GregTech port instead.

If anyone wanted to try and implement my idea, it was to try and have some of the Thaumcraft runes "etched" into the planks.

**Comment by lesdmark** [comment]
I like the direction your going I might take a stab at the greatwood and silverwood on my next day off

**Comment by Oddface** [comment]
I've now done Forestry, so that finishes up the biggest conversion jobs. Would be nice if we could get Extra Trees support at some point too. How's Thaumcraft coming along? The etching idea is cool, but it might be a little intense for a regular building material.

**Comment by lesdmark** [comment]
Since I have started on AE2 IF someone else wants to work on it that would be cool.

**Comment by Oddface** [comment]
I'll try doing the Thaumcraft planks and make something close to the default textures, which I think look pretty cool.

**Comment by goldbattle** [comment]
These are all looking good. If someone could push all the different color variations to the template repo, it might help out with things. Good stuff.

**Comment by lesdmark** [comment]
I'm going to close this as I think we got this all issue solved.
