### ISSUE TITLE
FoodPlus support

### ISSUE THREAD

**Issue by RofElMao** [John-Smith-Modded/JSTR-1.7.x#27]
Hi there. Firstly: I really love JSTR! <3 And since I don't like to use another pack and I'm not good at creating textures:
May one of you create textures for the "FoodPlus" mod by "JoseTheCrafter"? That'd be so nice :)

**Comment by lesdmark** [comment]
I realize the person who posted this probably won't see it but I'm going to see what I can do as far as support for the mod.

**Comment by lesdmark** [comment]
ok so this mod is buggy as hell. Closing the issue as I don't see a big demand to support a buggy mod

**Comment by RofElMao** [comment]
I've seen it ;) Yes, it's a bit buggy but somehow I still like that mod. Also if there'll now be officially no support for that mod, thanks for taking a look at it :)
