### ISSUE TITLE
BoP Grass

### ISSUE THREAD

**Issue by goldbattle** [John-Smith-Modded/JSTR-1.7.x#39]
Would be great to have this terrain added.
One of the best ways to make the game look good overall is to have the terrain textures covered.
[Link](http://i.imgur.com/PmEc1lv.gifv)

**Comment by goldbattle** [comment]
This has been fixed, good stuff!

**Comment by Oddface** [comment]
The dirt types haven't been done, but I don't think those will be implemented in world gen until the 1.8 version.
