### ISSUE TITLE
Broken transparencies in creative menu

### ISSUE THREAD

**Issue by Keetarin** [John-Smith-Modded/JSTR-1.7.x#42]
![capture](https://cloud.githubusercontent.com/assets/6365440/5602148/082af0da-92f7-11e4-8581-36f196e4af42.PNG)
Title says it all....

**Comment by goldbattle** [comment]
Could you give use a full mod list, and forge version? I know Soartex had a problem like this, and I think it was mod related. Not sure if we ever found a fix.

**Comment by goldbattle** [comment]
I found that it was reported to forge https://github.com/MinecraftForge/MinecraftForge/issues/1261 Not sure if it ever got fixed, but it can't get fixed now that forge for 1.7.x is closed for "major" issues.

**Comment by Keetarin** [comment]
It was on the latest direwolf20 pack for 1.7.10

**Comment by Keetarin** [comment]
latest direwolf20 pack for 1.7.10

**Comment by goldbattle** [comment]
This isn't something we can fix, it effects all 1.7.x packs with forge installed.
We will have to see if forge fixes it.
