### ISSUE TITLE
JSTR: Legacy Overwrite Patch

### ISSUE THREAD

**Issue by Oddface** [John-Smith-Modded/JSTR-1.7.x#43]
I remember there being talk of doing a version of this pack using the Legacy textures as a base, and I would just like to float this idea again. The problem with doing this is obviously the large amount of extra work it would create for a pretty small team. The way to mitigate this would be to simply limit it to the dirt and raw stone textures. It would get us most of the way to the classic John Smith look without splintering the style too much and creating a lot of extra work. The ores would be a sizeable workload, but not insurmountable. There are already these lovely copper and tin ores stuck in the alt texture ghetto.
![](https://raw.githubusercontent.com/John-Smith-Modded/JSTR-1.7.x/master/Tinker_Construct/assets/tinker/textures/blocks/ore_copper_alt.png)
![](https://raw.githubusercontent.com/John-Smith-Modded/JSTR-1.7.x/master/Tinker_Construct/assets/tinker/textures/blocks/ore_tin_alt.png)
I would certainly want this as an option and I think a lot of other people would too. What do you guys think?

**Comment by goldbattle** [comment]
I think this could work. Right now all what I do to compile the packs is apply the https://github.com/John-Smith-Modded/JSTR-Overwrites ontop of the normal vanilla release. I think this could be something that could be worked on a separate branch and worked on.

While this would allow vanilla and modded to look the same, but would take a lot of work to do. Maybe we could hold off till the 1.8.x update? I know the tin/dust redo is still in the works on the [Ore-Enhancement](https://github.com/John-Smith-Modded/JSTR-1.7.x/commits/Ore-Enhancement ) branch.

**Comment by Oddface** [comment]
This Legacy version would still have JSTR overwrites, just not the raw stone, dirt, grass, sand and ores. I don't really know the details of the back-end stuff you do, so I don't know the best way to do this. Is working on this in a branch practical in the long run? Can changes in the JSTR branch be merged into the Legacy branch easily? Could it be done in a separate repository of overwrites?

**Comment by goldbattle** [comment]
Just doing a separate branch like the ore one works great. Once it is all ready to go, it is as simple as merging it into the master, and recompiling the packs. I would check out my comment https://github.com/John-Smith-Modded/JSTR-1.7.x/pull/36#issuecomment-62541235 on mass recolors, might help speed things up.

**Comment by Oddface** [comment]
Well, I think I'm pretty much done with the essentials. The ores are all done (except Metallurgy) and I'm pretty happy with how they've turned out. Some improvements could still be made, like more variation in the ores, but I think I'll do that at a later date. There are also some minor niggles, like how the nether ores don't quite match up with the surface ores. Other stone types (marble, basalt etc.) do still have that JSTR look, but it still looks fine and I'd rather not mess around with those. Anything big I've missed? Any other naturally spawning blocks that are supposed to look like dirt, stone or sand?

**Comment by goldbattle** [comment]
I think they all look good. I think a couple of them look a bit like the ore texture was pasted on top, not sure if some shading could solve that. I would create a PR when you think these are all ready. If this is good to go, and other people think this is good, the next download I will remove the JSTR dirt, stone, and stone ore textures from the https://github.com/John-Smith-Modded/JSTR-Overwrites repo, and repatch it on top.

**Comment by Oddface** [comment]
Please do tell which textures you have concerns with and I'll have a look.

**Comment by Oddface** [comment]
Oh, and I suggest removing the sand from the overwrites as well.

**Comment by goldbattle** [comment]
Got it. 

Sorry about the response was going to edit my post, but got pulled away. Here are the ores I was going to comment on.

`Applied_Energistics_2/assets/appliedenergistics2/textures/blocks/OreQuartzStone.png`
![orequartzstone](https://cloud.githubusercontent.com/assets/2222562/5634608/39a37672-95af-11e4-94d6-c64153863a2f.png)
`Tinker_Construct/assets/tinker/textures/blocks/ore_aluminum_gravel.png`
![ore_aluminum_gravel](https://cloud.githubusercontent.com/assets/2222562/5634616/46ba9322-95af-11e4-9fae-45220f159443.png)
`Tinker_Construct/assets/tinker/textures/blocks/ore_iron_gravel.png`
![ore_iron_gravel](https://cloud.githubusercontent.com/assets/2222562/5634623/5221ee7c-95af-11e4-839c-d02d8317a2bb.png)

I feel like the elements are not a part of the texture below. Not sure the best way to fix it with the gravels. I think with the AE2 ore it is just the lack of texture on the actual crystal texture. Just some thoughts, nothing that neeeds to be fixed.

**Comment by Oddface** [comment]
Alright, I fixed the iron gravel ore and I'll leave the other stuff for later. I want to do something about the cobblestone, it just looks a little too flat compared to the Legacy stuff. I tried with the Legacy cobble, but that stood out too much, so I made some edited versions of the Legacy cobble with a little less contrast and JSTR coloring and I feel like it ended up bridging the gap between the two styles rather nicely.
![2015-01-10_18 59 03](https://cloud.githubusercontent.com/assets/7591428/5692559/d694ef4e-98fa-11e4-976f-7602bc046c26.png)

**Comment by goldbattle** [comment]
Just compiled and uploaded things, check them out before I put them up for main downloads.

Patch:
http://minecraft.curseforge.com/texture-packs/223328-john-smith-modded/files/2225235
Main pack:
http://minecraft.curseforge.com/texture-packs/223328-john-smith-modded/files/2225237

/cc @John-Smith-Modded/texturers @John-Smith-Modded/owners

**Comment by Oddface** [comment]
Everything seems to work. The name and description could be better, though. Maybe call it the JSTR Legacy Patch and mention the stone, dirt and sand in the description as well.

**Comment by goldbattle** [comment]
The description will be on the main site, I'll update it with details once
I type something up.

On Thu, Jan 22, 2015 at 3:29 PM, Oddface <notifications@github.com> wrote:

> Everything seems to work. The name and description could be better,
> though. Maybe call it the JSTR Legacy Patch and mention the stone, dirt and
> sand in the description as well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/John-Smith-Modded/JSTR-1.7.x/issues/43#issuecomment-71092613>
> .
>



-- 
Patrick Geneva | Administrator | pgb@soartex.net

**Comment by Oddface** [comment]
Here's a minor problem I just found.
![2015-01-22_21 46 55](https://cloud.githubusercontent.com/assets/7591428/5864198/5186bda2-a280-11e4-9251-62f1b3cf1747.png)
There are a few green pixels sticking out from under the grass side overlay, which is noticeable in non-green biomes.

**Comment by goldbattle** [comment]
Have any idea what is causing it?

**Comment by Oddface** [comment]
The grayscale grass overlay doesn't quite cover all the green grass on the grass side texture. I'm making a fix as we speak.

**Comment by goldbattle** [comment]
No rush, I am going to let this sit for a day so others can take a look at it, and give some feedback before we let it go live.

**Comment by goldbattle** [comment]
It's live. Let me know if any wording on the website should be better. This turned out to be pretty cool.

**Comment by Oddface** [comment]
Thank you for facilitating this little project. Makes me enjoy the pack a lot more!
