### ISSUE TITLE
Finish blood magic

### ISSUE THREAD

**Issue by lesdmark** [John-Smith-Modded/JSTR-1.7.x#46]
getting blood magic as complete as possible. Any texture ideas for things not already completed welcome. Trying to get through most of the main ones at least. New idea for the scribing tools would be most welcome.

**Comment by lesdmark** [comment]
I think I have done just about as much as I can with blood magic, anyone else feel free to finish up the other stuff. I may still work on it occasionally but I need a new mod to work on the textures and the IC2 menus are calling my name I think.

**Comment by goldbattle** [comment]
Overall, really impressed with everything. Amazing work!

I will close this for now, feel free to reopen as needed.
