### ISSUE TITLE
Backwards Bows

### ISSUE THREAD

**Issue by penguinsane** [John-Smith-Modded/JSTR-1.7.x#47]
The bows have been backwards (arrows pointing toward the player instead of away) for quite some time. Some in-game examples:

http://puu.sh/edfXD/0a9bad5f62.jpg

http://puu.sh/edfUl/e1727cf4f9.jpg

**Comment by Oddface** [comment]
The arrow sprites are facing the opposite way of the default texture pack, which isn't a problem in vanilla, but if there's some kind of mod that uses the arrow sprites in the drawing animation then I guess we'll need to make a JSTR overwrite that flips them.

**Comment by Oddface** [comment]
Which mod does this btw?

**Comment by penguinsane** [comment]
Whoops, I'm sorry! I should have figured that was the problem.

I believe that it is Mine & Blade that is doing this.

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1291267-mine-blade-battlegear-2-bullseye-1-0-6-3
