### ISSUE TITLE
Baubles GUI Button

### ISSUE THREAD

**Issue by penguinsane** [John-Smith-Modded/JSTR-1.7.x#50]
Mod: Baubles
Link: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1294623-baubles-1-1-0-0-updated-2014-1-6

Adds a little icon in the top right of the player portrait on the inventory screen, which is not visible in the current version of JSTR. Screenshot example...

http://puu.sh/ezj9x/f005ac421e.jpg

**Comment by Greenhawk837** [comment]
This should be fixed in this commit
https://github.com/John-Smith-Modded/JSTR-1.7.x/commit/9f48e6e59a87e59e43e2e3923ded771783b1bf6b

**Comment by goldbattle** [comment]
The main packs have not been updated in the past 2 weeks. When I get back
in a few days we will be rolling out some crazy changes to things with all
the updates. Hope this makes sense.

On Thu, Jan 15, 2015 at 11:53 PM, Greenhawk837 <notifications@github.com>
wrote:

> This should be fixed in this commit
> 9f48e6e
> <https://github.com/John-Smith-Modded/JSTR-1.7.x/commit/9f48e6e59a87e59e43e2e3923ded771783b1bf6b>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/John-Smith-Modded/JSTR-1.7.x/issues/50#issuecomment-70208270>
> .
>



-- 
Patrick Geneva | Administrator | pgb@soartex.net

**Comment by penguinsane** [comment]
Whups! I checked the commits and didn't see it right away, very sorry. Looking forward to the main pack updates, thank you!

**Comment by Greenhawk837** [comment]
That's alright. We don't expect you to know if it hasn't been in any pack updates.

Thanks for reporting bugs.
