### ISSUE TITLE
Minefactory Reloaded

### ISSUE THREAD

**Issue by goldbattle** [John-Smith-Modded/JSTR-1.7.x#53]
Not sure if this was ever changes, from the commit history, probably not.

> Seems somewhere in the 1.7.X cycle, Minefactory Reloaded changed file names and folders so that the JSTR textures no longer load properly. I took the current files and renamed them and created the folders needed the make them work in 1.7.10. I did create a few new textures for some things that were missing, but they are nothing spectacular. Here's the zip:
> http://www.mediafire.com/download/ahh623srw7yjbnn/Minefactory_Reloaded.zip

Check out the post [here](http://www.minecraftforum.net/forums/mapping-and-modding/resource-packs/1243222-john-smith-legacy-1-4-7-1-5-1-6-1-7-jstr-mod?comment=1643).

**Comment by Oddface** [comment]
Sam committed this 10 days ago.

**Comment by goldbattle** [comment]
Welp, should have not just looked at the first page, to many commits. Thanks, sorry about that.
