### ISSUE TITLE
Adding Mod.json

### ISSUE THREAD

**Issue by goldbattle** [John-Smith-Modded/JSTR-1.7.x#62]
So one of the things that Soartex has started to roll out is this idea of a mod.json. The idea behind it is that it is the start of the next patcher version. In this future version of the patcher, the user would be downloading the github repo, and interacting directly with it. So one way to get information about the mods is to use this small file called a `mod.json`. This file should be placed in the root of each mod folder.

We have a little post on it [here](http://soartex.github.io/modded/01-01-2015/making-a-mod-json/) as you could update mods its a small thing that would be great to add. It also provides a little way for contributors to keep track of the last version the mod was compatible with. This is not something that needs to be done, but it is something that would be planning for the future, and keep things organized.

You can see how we are currently using this on the soartex 1.7.x repo.
https://github.com/Soartex-Modded/Modded-1.7.x/tree/master/Advanced_Genetics

Thanks again!

/cc @John-Smith-Modded/owners @John-Smith-Modded/texturers

**Comment by ScottKillen** [comment]
:+1:

**Comment by lesdmark** [comment]
Sounds good to me!

**Comment by Oddface** [comment]
And over a year later, finally done :)
