### ISSUE TITLE
JSTR64x Overwrites Pack

### ISSUE THREAD

**Issue by Greenhawk837** [John-Smith-Modded/JSTR-1.7.x#65]
I've been using a lot of 64x textures in my pack and instead of just keeping them to myself I thought I would start other repo over in [John-Smith-64x](https://github.com/John-Smith-64x).

I'm not sure how much I will work on it, but I do have plans to at least make all of the ingots, dusts and ores in 64x sometime in the near future.

I've just pushed the first commit for BoP [here](https://github.com/John-Smith-64x/JSTR64x-Overwrites/commit/37fa51be01e80ddefc0f34500c01b72624732659)

Just thought I would let you guys know, incase anyone was interested!

**Comment by ScottKillen** [comment]
Very nice!

**Comment by goldbattle** [comment]
Next update, I will just include this pack on the modded patch table on the bottom of the [modded](http://js-legacy.net/jstr-modded/) page.

**Comment by goldbattle** [comment]
Forgot to add, that I really like all the textures pushed, really impressed by them!

**Comment by Greenhawk837** [comment]
Thanks! Do you want me to include the vanilla textures in the overwrites repo as well, so everything is all in the same place for a patch?

**Comment by goldbattle** [comment]
I have not figured that part out yet, for now just keep it separate.

On Sat, Feb 14, 2015 at 11:29 PM, Sam <notifications@github.com> wrote:

> Thanks! Do you want me to include the vanilla textures in the overwrites
> repo as well, so everything is all in the same place for a patch?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/John-Smith-Modded/JSTR-1.7.x/issues/65#issuecomment-74403647>
> .
>



-- 
Patrick Geneva | Administrator | pgb@soartex.net

**Comment by goldbattle** [comment]
For now, this will be a patch on the website, just compiled it, and it will go live in a bit.
