### ISSUE TITLE
Stone textures

### ISSUE THREAD

**Issue by lesdmark** [John-Smith-Modded/JSTR-1.7.x#69]
I noticed as I was looking at the stone textures that were added for chisel that they are very bold looking. I also noticed the reason was that they were based on the ones for underground biomes. Does anyone think maybe we should try to soften them up a bit or are they ok? Something more like the marble and basalt in project red whilst still respecting the type of stone it's based on.

**Comment by ScottKillen** [comment]
I added them and then in gem felt exactly the same as you. The same textures are used for gany's mod as well. The 1.8.1 legacy pack has some textures that would work (basically recolored stone.) I'll see what I can do (but I'll use JSTR stone.)

**Comment by Oddface** [comment]
This is kind of an aside, but I'll just put here. The marble in project red is just a placeholder from faithful 32 and it kind of shows. We should replace all instances of that with the chisel marble sam just updated.

**Comment by lesdmark** [comment]
I think the marble bricks are ok though. and maybe add a bit of veining in the marble in chisel?

**Comment by Oddface** [comment]
Yeah, I was only talking about the raw marble. After thinking more about it I could see how someone would want something different from the Project Red marble, as it's pretty widely used as a building material in its raw form. The default texture is a lot smoother than Chisel's raw marble. But then again, Chisel is pretty much standard for mod packs nowadays so I don't how much it really matters.

**Comment by Greenhawk837** [comment]
After I update the chisel marble brick, what would people think about replacing the project red marble bricks with the old chisel ones, I find they look much nicer, since they don't have that black border throughout them.

And some veining might look good in the marble, I'll see what I can come up with.

**Comment by goldbattle** [comment]
I think this by @ScottKillen reopen if needed.
