### ISSUE TITLE
Let's talk about cobblestone!

### ISSUE THREAD

**Issue by Oddface** [John-Smith-Modded/JSTR-1.7.x#71]
Alright, last time I'm going to propose major fundamental changes to the pack, probably. The current cobblestone has been around since the start of JSTR and while a lot of the pack evolved, it stayed the same, and now I just think it looks out of place. It's too bland and low-contrast compared to other stuff, like the planks for example. I'm gonna throw out some options here and see what you think. Additional suggestions are welcome.

original cobblestone
![cobblestone](https://cloud.githubusercontent.com/assets/7591428/5992766/458e94f2-aa37-11e4-9e36-d161919bcf03.png)
original cobblestone with higher contrast
![cobblestone](https://cloud.githubusercontent.com/assets/7591428/5992768/537fc040-aa37-11e4-8cee-c660144e887b.png)
a more flat variant that is used for some stone types in the pack already
![cobblestone](https://cloud.githubusercontent.com/assets/7591428/5992771/765d9ea2-aa37-11e4-8798-de7e8f60a266.png)
Legacy cobble with JSTR colors
![cobblestone](https://cloud.githubusercontent.com/assets/7591428/5992798/7b6dd6fe-aa38-11e4-8db0-3816688429be.png)
Same as above slightly modified and with lower contrast
![cobblestone](https://cloud.githubusercontent.com/assets/7591428/5992867/8e886abc-aa3b-11e4-8437-e05861067384.png)

The Legacy cobble does have the advantage of built in mcpatcher support, which would be extra nice when 1.8 rolls around.

**Comment by ScottKillen** [comment]
I prefer both the higher contrast original and the recolored legacy. I suppose the recolored legacy would win between the two because of the MCPatcher support (even though it is very difficult to run MCPatcher or Optifine with other mods--meaning not all mods play well with them.)

**Comment by Oddface** [comment]
The mcpatcher stuff is going to be a way bigger deal in 1.8 where randomized textures and block specific textures are a part of vanilla.

**Comment by ScottKillen** [comment]
Seems like that is the answer then.

**Comment by Oddface** [comment]
My only concern is that the Legacy cobble stands out a little too much in JSTR. It's very high contrast. If you take the mcpatcher thing out of the equation, I think the higher contrast version of the original makes the most sense stylistically, but I think the tiling is kinda bad. I can't be the only one that sees a peace sign in the current cobblestone, can I?

**Comment by lesdmark** [comment]
I don't care for the legacy cobble and I agree it's too high contrast. I like the flat, and the original with more contrast if were going to be changing it. I think the challenge with stones and such is to make sure whatever doesn't look grainy and pixelated. The trick with JSTR is nothing can look too smooth or perfect it all needs to be just a bit imperfect to work well. It's the reason I like the pack so much

**Comment by Greenhawk837** [comment]
Personally I'm happy with the cobblestone the way it is. The original with more contrast wouldn't look too bad though if it was still the same grey colour as the original.

**Comment by Oddface** [comment]
Here's an older cobble texture that I edited a bit. It's pretty close to the current texture, but with more contrast and little cleaner (and no peace sign!)
![cobblestone](https://cloud.githubusercontent.com/assets/7591428/5994415/ba437a16-aa72-11e4-87d7-0d6a7a957650.png)

**Comment by Greenhawk837** [comment]
That does look really nice! I'll have to check it out ingame.

**Comment by Satellence** [comment]
In game i use that cobble texture with chiseled variations:
![2015-02-02_11 48 06](https://cloud.githubusercontent.com/assets/1390832/5997200/1a4c5a94-aac9-11e4-982e-d0a7d31fe19c.png)

I think cobble its fine, better to talk about smoothstone and stone bricks texture.
With chisel mod chiseled cobble look jist like stone bricks

**Comment by Oddface** [comment]
Really awesome textures, @Satellence! We will try to find something that looks very close to the old cobblestone texture. It doesn't need to be a big change, I just think it could look better.

**Comment by Greenhawk837** [comment]
I agree, those textures look great @Satellence!

**Comment by ScottKillen** [comment]
Wow!

**Comment by Oddface** [comment]
Made some tweaks. It's a little closer to the original and it should tile better from a distance.
![cobblestone](https://cloud.githubusercontent.com/assets/7591428/6001449/2ce852fe-aaea-11e4-964d-0e80554d2f22.png)
@Satellence Would you like to change the stone bricks? I don't have an issue with them personally, but now that we have the cobble bricks, maybe the normal bricks could be a little cleaner? I would like to hear your suggestions.

**Comment by ScottKillen** [comment]
:+1: to that idea!

**Comment by Satellence** [comment]
WIP stone bricks texture. I experementing with brightness and cracks contrast
![Uploading bricks.png . . .]()

**Comment by ScottKillen** [comment]
What is the solid block on the top right?

**Comment by Satellence** [comment]
One of the chiseled cobblestone
https://github.com/John-Smith-Modded/JSTR-1.7.x/commit/717855aaeb4dec46fa96b94332162b721b1cfa32

**Comment by Oddface** [comment]
The strong black lines makes it look a little too clean and modern for me.

**Comment by lesdmark** [comment]
Just a bit more roughness to the lines on the stone bricks and a tiny bit less contrast on the lines and I would say it's just about perfect. I do like the texture though.

**Comment by Oddface** [comment]
I've been staring at this texture for too long. Can anyone tell me if it's any good or not? 
![cobblestone](https://cloud.githubusercontent.com/assets/7591428/6010135/482b24ba-ab30-11e4-9a32-c419d01490fa.png)

**Comment by lesdmark** [comment]
Looks pretty good to me.

**Comment by Oddface** [comment]
Since it seems I'm the only one that has any real issue with the current cobble, I just want to make sure I'm not pushing for a change that anyone would dislike.

**Comment by ScottKillen** [comment]
There are days when I like the current cobble and days when I don't. I vote for the change.

**Comment by goldbattle** [comment]
I am not sure I follow this conversation, but what do I need to change on the pack? I know there is probably some ctm for the cobble texture in the base pack etc, but what do I need to edit for the next release. I want to get an updated pack, and the 64x pack updated this weekend.

**Comment by Oddface** [comment]
It's yet to be decided, so nothing needs to be changed for now. I'm still working on it.

**Comment by Glowstrontium** [comment]
I did make some (admittedly crude) CTM textures for the current JSTR cobble and stone bricks a long time ago - I have no idea if they're still included, or have been lost somewhere along the transition.

**Comment by goldbattle** [comment]
They should be.

On Sat, Feb 14, 2015 at 4:28 PM, Glowstrontium <notifications@github.com>
wrote:

> I did make some (admittedly crude) CTM textures for the current JSTR
> cobble and stone bricks a long time ago - I have no idea if they're still
> included, or have been lost somewhere along the transition.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/John-Smith-Modded/JSTR-1.7.x/issues/71#issuecomment-74392731>
> .
>



-- 
Patrick Geneva | Administrator | pgb@soartex.net

**Comment by lesdmark** [comment]
I think this has been discussed and dealt with for now. Closing the issue we can reopen if needed later.
