### ISSUE TITLE
Applied Energistics Crafting Status

### ISSUE THREAD

**Issue by CaptainHawaii** [John-Smith-Modded/JSTR-1.7.x#72]
Does anyone know where and what is causing the missing texture glitch on the Crafting Terminal's Crafting Status button?

**Comment by Oddface** [comment]
Screenshot, please? Are you using the latest version of the pack?

**Comment by CaptainHawaii** [comment]
![2015-02-02_14 27 02](https://cloud.githubusercontent.com/assets/455000/6007406/bea3ff02-aae7-11e4-8e28-e9ead5482135.png)

**Comment by Oddface** [comment]
We already have an issue that deals with this here: https://github.com/John-Smith-Modded/JSTR-1.7.x/issues/15. @lesdmark is on it.

**Comment by lesdmark** [comment]
Should have some corrections ready soon at least
