### ISSUE TITLE
Customizer Files

### ISSUE THREAD

**Issue by goldbattle** [John-Smith-Modded/JSTR-1.7.x#80]
I have had this for a while, but it just dawned on me when looking at the chisel commits that you guys might not have these. I am only going to keep the download up for a couple days, so please download the zip [here](https://drive.google.com/file/d/0B9VccKUBwE88OHluamswMm1JYlE/view?usp=sharing). Files are from the last version of the customizer from back in the day. They are covered by the same john smith license.

/cc @John-Smith-Modded/texturers

**Comment by Oddface** [comment]
Nice! I had the alt texture sheets that were posted on the forums, but they were missing some stuff.

**Comment by Greenhawk837** [comment]
Yeah, very nice! I haven't seen some of these textures in years.

**Comment by ScottKillen** [comment]
:+1: Thanks!!! (I have these buried in various releases, but it is nice to have them in one place)
