### ISSUE TITLE
AE2 Gui changes

### ISSUE THREAD

**Issue by lesdmark** [John-Smith-Modded/JSTR-1.7.x#85]
So I have been working on a GUI change for AE2 that is still very JSTR but gives the GUI a more techy feel I think is needed for AE2. I wanted to get some feedback before I changed all of them 
![bus](https://cloud.githubusercontent.com/assets/7751260/6321761/145a9168-bad3-11e4-9d87-f40df8326ac5.png)

**Comment by Greenhawk837** [comment]
Personally I really like that!

**Comment by lesdmark** [comment]
Thanks! I try to make them a bit different whilst still respecting the design of the JSTR GUI.

**Comment by goldbattle** [comment]
I really like the color.

On Sun, Feb 22, 2015 at 8:45 PM, lesdmark <notifications@github.com> wrote:

> Thanks! I try to make them a bit different whilst still respecting the
> design of the JSTR GUI.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/John-Smith-Modded/JSTR-1.7.x/issues/85#issuecomment-75479045>
> .
>



-- 
Patrick Geneva | Administrator | pgb@soartex.net

**Comment by Oddface** [comment]
I like it! A way better fit for this mod than the usual stones and sticks look.

**Comment by ArfourFoulkesayke** [comment]
That's really nice. :+1:

**Comment by lesdmark** [comment]
So then that settles that I will go ahead and change them and also finish the GUI's for the ones that don't have one.
