### ISSUE TITLE
Hello, I would like to share you I painted textures

### ISSUE THREAD

**Issue by Morfcraft** [John-Smith-Modded/JSTR-1.7.x#89]
Hello,
I play Minecraft with your texture packs and thank your very march for your hard work .
And I would like to share you I painted textures in style of your texture pack, 
that other plaers can use they.

Textures: gregtech, ic2, magicalcrops, thermalexpansion, thermalfoundation 

https://drive.google.com/file/d/0Bz4tzEVdZSFraTdoQXRrYlBUVms/view?usp=sharing

Have a nice day.
Morfcraft

**Comment by Greenhawk837** [comment]
Wow really amazing work on these! I'll upload them to the repo

**Comment by goldbattle** [comment]
Wow this stuff is great, amazing job on it! :+1:

**Comment by Morfcraft** [comment]
Thank you. Soon I finish textures for GregTech.

**Comment by Morfcraft** [comment]
Hello, add on Gregtech + Malisisdoors https://drive.google.com/file/d/0Bz4tzEVdZSFrdXd3cXRCMVh1c3c/view?usp=sharing

**Comment by Greenhawk837** [comment]
That carriage door looks incredible, great stuff!
