### ISSUE TITLE
Tinker's Construct Hearts

### ISSUE THREAD

**Issue by Wallets** [John-Smith-Modded/JSTR-1.7.x#93]
It was driving me sort of mental that the extra hearts from Tinker's Construct heart canisters looked messed up, so I fixed them real quick (tinker/textures/gui/newhearts.png):
![newhearts](https://cloud.githubusercontent.com/assets/6297367/6786177/01f1edec-d161-11e4-903b-6b8d74f640d4.png)

**Comment by Oddface** [comment]
Committed. Thank you!
