### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by ArfourFoulkesayke** [John-Smith-Modded/JSTR-1.7.x#96]
I noticed that the download is still Version 0.1.14. We had quite a few commissions lately, is there another update scheduled?

**Comment by Greenhawk837** [comment]
Yeah, that would be good, I believe it has been over a month since the last update.

**Comment by goldbattle** [comment]
I'll try to get them updated this weekend.

**Comment by ArfourFoulkesayke** [comment]
Good job! :+1:

**Comment by goldbattle** [comment]
I updated the downloads, let me know if you run into any problems with them.

**Comment by ArfourFoulkesayke** [comment]
Are you sure you've updated them? I just downloaded version 0.1.15 from here: http://js-legacy.net/jstr-modded/ and is literally the same file as the one I've downloadad in early march. The number changed, but the .zip didn't. It's the same by the kilobyte.

**Comment by goldbattle** [comment]
Opps, seems I didn't update the link for that one, this should be fixed with https://github.com/John-Smith-Modded/john-smith-modded.github.io/commit/d7271d218e0ddf4d59a9c21206bb3c09abb14125 . The new file size should be around 106mb. Good catch, I'm usually better about not doing that.

**Comment by ArfourFoulkesayke** [comment]
So ... last version is from may 30th. Guess it's time for another update?

**Comment by ScottKillen** [comment]
Don't forget to refresh the base from Jim Stone per https://github.com/John-Smith-Modded/JSTR-1.7.x/issues/122
