### ISSUE TITLE
Thaumcraft Aspect Cost Text

### ISSUE THREAD

**Issue by AngelKairi** [John-Smith-Modded/JSTR-1.7.x#99]
Err, just a request for the bigger text on Thaumcraft aspects in the book/where it's usually small. I can still read the text in the book, for normal explainations and stuff for it, but the aspects, not so much. 

This is in 'normal' GUI settings. (Not all of us like playing in large. hehe)

Normal GUI Screenshot of an Example Page
![rsndyvj](https://cloud.githubusercontent.com/assets/4471184/7108286/8b42dafe-e14f-11e4-8bc4-f3875affdda9.png)

Large GUI Screenshot of an Example Page
![sdfasd5fa](https://cloud.githubusercontent.com/assets/4471184/7108296/e1d0c52a-e14f-11e4-94f9-ca50562c2c6f.png)

This is /with/ the patch installed, also. Is it possible to increase the size of the aspect numbers?

**Comment by Oddface** [comment]
There's not much we can do about this other than changing the whole font, which was discussed here: https://github.com/John-Smith-Modded/JSTR-1.7.x/issues/51. Small text in Minecraft is almost always in unicode (the default Minecraft font), but not here for some reason. You could ask the mod maker to change that.

**Comment by AngelKairi** [comment]
Probably could, thanks for explaining it though. <3
